
server:
  port: 8090



via-cep:
  url: https://viacep.com.br/ws/
stubby:
  url: http://localhost:8882/ 
  
  
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queue:
     new-address: queue.new-address